# Generated by Django 5.2.3 on 2025-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0005_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='leak_detection_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_tyre',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
