# Generated by Django 5.2.3 on 2025-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0006_service_leak_detection_price_service_price_per_tyre'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_basic',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_bharat_dc',
            field=models.DecimalField(decimal_places=2, default=180, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_ccs',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_chademo',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_type2',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
