# Generated by Django 5.2.3 on 2025-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0007_service_price_basic_service_price_bharat_dc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_brake_issues',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_chain_belt',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_clutch_gear',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_dead_battery',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_electrical',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_flat_tyre',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_fluid_leak',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_key_lockout',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_overheating',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_starter_motor',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
    ]
