# Generated by Django 5.2.3 on 2025-06-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0009_customuser_agent_status_customuser_id_proof_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='agent_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_proof_file',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_proof_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_proof_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_agent',
        ),
    ]
