# Generated by Django 5.2.3 on 2025-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0010_remove_customuser_agent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('id_proof_type', models.CharField(max_length=50)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('id_proof_file', models.FileField(upload_to='agent_id_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
