# Generated by Django 5.2.3 on 2025-06-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0011_agentregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=10),
        ),
    ]
