# Generated by Django 5.2.3 on 2025-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0012_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedAgentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
