# Generated by Django 5.2.3 on 2025-08-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
